data:
  extra_args: None
  label_type: pcdet
  path: D:\datasets\shahbaz\datasets\pedsafe_human_labeled
  range:
  - -5
  - -5
  - -5
  - 5
  - 5
  - 5
  rotation:
  - 0
  - 0
  - 0
  size: 100
  type: .npy
debug:
  asyncio_sleep: 0.01
process:
  background:
    D_HistDPPFilter:
      background_bins: 10
      bin_height_threshold: 0.1
      distance_threshold: 0.1
      pcd_size: 1000
      query_size: 10
      total_bins: 100
    SimplePlaneModelBasedFilter:
      model:
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      query_size: 1
      threshold: 0.1
    SimpleVoxelDensityFilter:
      query_size: 100
      threshold: 0.1
      voxel_size:
      - 0.1
      - 0.1
      - 0.1
    selected:
    - SimplePlaneModelBasedFilter
    - SimpleVoxelDensityFilter
  bbox:
    regressor:
      SimpleBBoxRegressor:
        type: Oriented
      selected: SimpleBBoxRegressor
    validator:
      SimpleBBoxValidator:
        max_b: 6.0
        max_h: 1.8
        max_z_location: -4.0
        min_b: 0.2
        min_h: 0.6
      selected: SimpleBBoxValidator
  classifier:
    SimpleSizeBasedClassifier:
      Car:
      - base_length
      - height
      Pedestrian:
      - height
      - base_length
      Targets:
      - Car
      - Pedestrian
    SimpleVolumeBasedClassifier:
      Car:
      - 10
      - 20
      Cyclist:
      - 1.75
      - 4.0
      Pedestrian:
      - 0.25
      - 1.5
      Targets:
      - Car
      - Pedestrian
      - Cyclist
    selected: SimpleVolumeBasedClassifier
  cluster:
    DBSCANClusteringAlgo:
      eps: 0.6
      min_pts: 4
    selected: DBSCANClusteringAlgo
visualize:
  bbox_colors:
    Car:
    - 1
    - 0
    - 0
    Cyclist:
    - 0
    - 0
    - 1
    GT_Car:
    - 0.25
    - 0.0
    - 0.0
    GT_Cyclist:
    - 0
    - 0
    - 0
    GT_Pedestrian:
    - 0.25
    - 0.25
    - 0.0
    Pedestrian:
    - 1
    - 1
    - 0
  bound_color:
  - 0
  - 0
  - 1
  point_color:
  - 1
  - 1
  - 1
  point_size: 1.0
  space_color:
  - 0
  - 0
  - 0
